name: Tests

on: [push, pull_request]

env:
  DJANGO_SETTINGS_MODULE: cdc_portal.settings
  DJANGO_SECRET_KEY: "dcyz)+52d)n1f3d6dsf&g0p6a($(v4&rvu=9u3u6fib9=kzy$8"

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: cdcuser
          POSTGRES_PASSWORD: cdcpassword
          POSTGRES_DB: cdcdb
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup environment variables
      run: |
        cp .env.example .env
        export DJANGO_SETTINGS_MODULE=cdc_portal.settings
    - name: Install dependencies
      working-directory: ./backend
      run: |
        sudo apt-get install libpq-dev 
        pip3 install coverage
        pip3 install pipenv
    - name: Linting
      working-directory: ./backend
      run: |
        pipenv install --dev
        source "$(pipenv --venv)"/bin/activate
        flake8 .
    - name: Migrations
      working-directory: ./backend
      run: |
        source "$(pipenv --venv)"/bin/activate
        python manage.py makemigrations student
        python manage.py migrate student
        python manage.py makemigrations
        python manage.py migrate
    - name: Coverage
      working-directory: ./backend
      run: |
        source "$(pipenv --venv)"/bin/activate
        pip3 install coverage
        coverage run --source='.' manage.py test
  
